[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x565575"
blue = "0x65b2ff"
cyan = "0x63f2f1"
green = "0x62d196"
magenta = "0x906cff"
red = "0xff5458"
white = "0x565575"
yellow = "0xffb378"

[colors.normal]
black = "0x100e23"
blue = "0x004be3"
cyan = "0xaaffe4"
green = "0x07f985"
magenta = "0x252433"
red = "0xff1b45"
white = "0x07f985"
yellow = "0xfde802"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
# decorations = "none"
# opacity = 0.9
x = 10
y = 10
